### ISSUE TITLE
Курсор в строке адреса

### ISSUE THREAD

**Issue by rizzak** [sglazov/empty-tab#2]
Прошу сделать так чтобы по умолчанию курсор ввода вставал в строку адреса.

**Comment by sglazov** [comment]
@rizzak, но сейчас по-умолчанию поведение браузера устроено так, что при открытии новой вкладке курсор будет установлен в адресной строке.

У вас не такое поведение?

**Comment by rizzak** [comment]
Да, все так и работает, что то видимо глюкануло.
